name: Unity Pipeline

on:
  push:
    branches: [ "pipelineTest" ]
  pull_request:
    branches: [ "development" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
    
      # - uses: actions/cache@v3
      #   with:
      #     path: ./UnityProject/WhileYoureHere/Library
      #     key: Library-WhileYoureHere-WebGL
      #     restore-keys: |
      #       Library-WhileYoureHere-
      #       Library-
    
      - name: Build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          projectPath: ./UnityProject/WhileYoureHere

      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: Build
      #     path: build